/*
 * Copyright (c) 2018 Rain Agency <contact@rain.agency>
 * Author: Rain Agency <contact@rain.agency>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
export const AGENT = {
  description: "description",
  activeAssistantAgents: [],
  disableInteractionLogs: false,
  googleAssistant: {
    googleAssistantCompatible: true,
    project: "project",
    welcomeIntentSignInRequired: false,
    systemIntents: [],
    oAuthLinking: {
      required: false,
      grantType: "AUTH_CODE_GRANT"
    },
    voiceType: "MALE_1",
    capabilities: [],
    protocolVersion: "V2",
    autoPreviewEnabled: true,
    isDeviceAgent: false
  },
  defaultTimezone: "America/New_York",
  webhook: {
    url: "webhook.url",
    headers: {},
    available: true,
    useForDomains: true,
    cloudFunctionsEnabled: false,
    cloudFunctionsInitialized: false
  },
  isPrivate: true,
  customClassifierMode: "use.after",
  mlMinConfidence: 0.2,
  supportedLanguages: [],
  onePlatformApiVersion: "v2beta1"
};

export const BUILT_IN_INTENTS_LIST: string[] = [
  "HelpIntent",
  "StopIntent",
  "CancelIntent",
  "YesIntent",
  "NoIntent",
  "PauseIntent",
  "ResumeIntent",
  "RepeatIntent",
  "StartOverIntent",
  "PreviousIntent",
  "NextIntent",
  "LoopOffIntent",
  "LoopOnIntent",
  "ShuffleOffIntent",
  "ShuffleOnIntent"
];

export const BUILT_IN_INTENTS: any = {
  en: {
    HelpIntent: ["help", "help me", "can you help me"],
    StopIntent: ["stop", "off", "shut up"],
    CancelIntent: ["cancel", "never mind", "forget it"],
    YesIntent: [
      "okay",
      "of course",
      "i don't mind",
      "do it",
      "ok",
      "sounds good",
      "confirm",
      "that's correct",
      "I agree",
      "exactly",
      "yes",
      "yes please",
      "sure"
    ],
    NoIntent: [
      "no",
      "I disagree",
      "not really",
      "not interested",
      "I don't want that",
      "I don't think so",
      "definitely not",
      "don't do it",
      "no thanks"
    ],
    PauseIntent: ["pause", "pause that"],
    ResumeIntent: ["continue", "resume", "continue", "keep going"],
    RepeatIntent: ["repeat", "say that again", "repeat that"],
    StartOverIntent: ["start over", "restart", "start again"],
    PreviousIntent: ["go back", "skip back", "back up"],
    NextIntent: ["next", "skip", "skip forward"],
    LoopOffIntent: ["loop off"],
    LoopOnIntent: ["loop", "loop on", "keep playing this"],
    ShuffleOffIntent: ["stop shuffling", "shuffle off", "turn off shuffle"],
    ShuffleOnIntent: ["shuffle", "shuffle on", "shuffle the music", "shuffle mode"]
  },
  de: {
    HelpIntent: ["Hilfe", "Hilf mir", "können Sie mir helfen"],
    StopIntent: ["halt", "aus", "halte den Mund, halt den Rand, Halt die Klappe"],
    CancelIntent: ["stornieren", "keine Ursache", "Vergiss es"],
    YesIntent: [
      "OK",
      "natürlich",
      "es ist mir egal",
      "Tu es",
      "in Ordnung",
      "klingt gut",
      "bestätigen",
      "das ist richtig",
      "Genau",
      "genau",
      "Und es ist",
      "ja bitte",
      "sicher"
    ],
    NoIntent: [
      "Nein",
      "Ich bin nicht einverstanden",
      "nicht wirklich",
      "nicht interessiert",
      "ich möchte das nicht",
      "no lo creo",
      "Definitiv nicht",
      "TU es nicht",
      "Nein Danke"
    ],
    PauseIntent: ["fortsetzen", "fortsetzen", "fortsetzen", "mach weiter"],
    ResumeIntent: ["wiederholen", "Sag das nochmal", "wiederhole das"],
    RepeatIntent: ["Von vorn anfangen", "Neustart", "nochmal beginnen"],
    StartOverIntent: ["Von vorn anfangen", "Neustart", "nochmal beginnen"],
    PreviousIntent: ["geh zurück", "überspringen zurück", "untermauern"],
    NextIntent: ["Nächster", "überspringen", "nach vorne spulen"],
    LoopOffIntent: ["Schleife aus"],
    LoopOnIntent: ["Schleife", "Schlaufe an", "halten diese spielen"],
    ShuffleOffIntent: ["Stopp-Shuffling", "abwälzen", "ausschalten Shuffle"],
    ShuffleOnIntent: ["Mischen", "Shuffle auf", "mische die Musik", "Shuffle-Modus"]
  },
  es: {
    HelpIntent: ["ayuda", "ayuadame", "me puedes ayudar"],
    StopIntent: ["detener", "apagado", "Cállate"],
    CancelIntent: ["cancelar", "no importa", "olvídalo"],
    YesIntent: [
      "bueno",
      "por supuesto",
      "no me importa",
      "hazlo",
      "Okay",
      "suena bien",
      "confirmar",
      "eso es correcto",
      "estoy de acuerdo",
      "exactamente",
      "si",
      "sí por favor",
      "Por supuesto"
    ],
    NoIntent: [
      "No",
      "Estoy en desacuerdo",
      "realmente no",
      "no interesado",
      "No quiero que",
      "No lo creo",
      "definitivamente no",
      "no lo haga",
      "no, gracias"
    ],
    PauseIntent: ["pausa", "Suspender la"],
    ResumeIntent: ["Seguir", "currículum", "Seguir", "sigue adelante"],
    RepeatIntent: ["repetir", "Repitelo", "repite eso"],
    StartOverIntent: [" comenzar de nuevo", "reiniciar", "empezar de nuevo"],
    PreviousIntent: ["regresa", "saltar hacia atrás", "apoyo"],
    NextIntent: ["siguiente", "omitir", "saltar hacia adelante"],
    LoopOffIntent: ["fuera del bucle"],
    LoopOnIntent: ["lazo", "lazo en", "seguir jugando este"],
    ShuffleOffIntent: [
      "interrumpir la reproducción aleatoria",
      "irse arrastrando los pies",
      "apague aleatoria"
    ],
    ShuffleOnIntent: ["barajar", "ponerse rápidamente", "mezclar la música", "modo aleatorio"]
  },
  ja: {
    HelpIntent: ["助けて", "助けて", "手伝って頂けますか"],
    StopIntent: ["やめる", "オフ", "黙れ"],
    CancelIntent: ["キャンセル", "気にしないで", "忘れてください"],
    YesIntent: [
      "はい",
      "もちろん",
      "私は気にしません",
      "やれ",
      "OK",
      "いいですね",
      "確認",
      "そのとおりです",
      "同意する",
      "丁度",
      "はい",
      "はい、お願いします",
      "承知しました"
    ],
    NoIntent: [
      "番号",
      "同意しません",
      "あんまり",
      "興味がありません",
      "私はそれが欲しくありません。",
      "私はそうは思いません",
      "絶対にありません",
      "それをしません",
      "結構です"
    ],
    PauseIntent: ["休止", "それを一時停止"],
    ResumeIntent: ["継続する", "履歴書", "継続する", "立ち止まるな"],
    RepeatIntent: ["繰り返す", "もう一度言って", "もう一度"],
    StartOverIntent: ["やり直します", "再起動", "再開する"],
    PreviousIntent: ["戻る", "バックスキップ", "バックアップ"],
    NextIntent: ["次", "スキップ", "早送り"],
    LoopOffIntent: ["ループオフ"],
    LoopOnIntent: ["ループ", "上のループ", "これを再生し続けます"],
    ShuffleOffIntent: ["ストップ・シャッフル", "脱ぎ捨てます", "シャッフルをオフにします"],
    ShuffleOnIntent: ["シャッフル", "上のシャッフル", "音楽をシャッフル", "シャッフルモード"]
  },
  fr: {
    HelpIntent: ["Aidez-moi", "Aidez moi", "Pouvez-vous m'aider"],
    StopIntent: ["Arrêtez", "de", "tais-toi"],
    CancelIntent: ["Annuler", "ça ne fait rien", "oublie"],
    YesIntent: [
      "d'accord",
      "bien sûr",
      "Je ne me dérange pas",
      "fais le",
      "D'accord",
      "ça m'a l'air bien",
      "confirmer",
      "c'est correct",
      "je suis d'accord",
      "exactement",
      "Oui",
      "Oui s'il vous plaît",
      "sûr"
    ],
    NoIntent: [
      "non",
      "je ne suis pas d'accord",
      "pas vraiment",
      "pas intéressé",
      "Je ne veux pas que",
      "Je ne pense pas",
      "définitivement pas",
      "ne pas le faire",
      "Non merci"
    ],
    PauseIntent: ["pause", "pause que"],
    ResumeIntent: ["continuer", "CV", "continuer", "continue"],
    RepeatIntent: ["répéter", "répète ça", "répète ça"],
    StartOverIntent: ["recommencer", "redémarrer", "recommencer"],
    PreviousIntent: ["retourner", "revenir en arrière", "sauvegarder"],
    NextIntent: ["suivant", "sauter", "sauter vers l'avant"],
    LoopOffIntent: ["boucle off"],
    LoopOnIntent: ["boucle", "boucle sur", "continuer à jouer ce"],
    ShuffleOffIntent: ["arrêt brassage", "rejeter", "désactiver lecture aléatoire"],
    ShuffleOnIntent: ["battage", "melanger sur", "mélanger la musique", "mode aléatoire"]
  },
  it: {
    HelpIntent: ["Aiuto", "aiutami", "Mi potete aiutare"],
    StopIntent: ["fermare", "via", "sta 'zitto"],
    CancelIntent: ["Annulla", "non importa", "Dimenticalo"],
    YesIntent: [
      "va bene",
      "ovviamente",
      "non mi dispiace",
      "fallo",
      "ok",
      "suona bene",
      "Confermare",
      "è corretto",
      "sono d'accordo",
      "Esattamente",
      "sì",
      "sì grazie",
      "sicuro"
    ],
    NoIntent: [
      "no",
      "non sono d'accordo",
      "non proprio",
      "non interessato",
      "Non voglio che",
      "Io non la penso così",
      "sicuramente non",
      "non farlo",
      "No grazie"
    ],
    PauseIntent: ["pausa", "pausa che"],
    ResumeIntent: ["Continua", "curriculum vitae", "Continua", "Continua così"],
    RepeatIntent: ["ripetere", "dire che ancora una volta", "ripetilo"],
    StartOverIntent: ["ricominciare", "ricomincia", "ricomincia"],
    PreviousIntent: ["torna indietro", "saltare indietro", "eseguire il backup"],
    NextIntent: ["Il prossimo", "Salta", "saltare avanti"],
    LoopOffIntent: ["ciclo off"],
    LoopOnIntent: ["ciclo continuo", "loop su", "continuare a giocare questo"],
    ShuffleOffIntent: [
      "interrompere la riproduzione casuale",
      "mischiare off",
      "spegnere riordino"
    ],
    ShuffleOnIntent: [
      "rimescolare",
      "mescolare su",
      "mescolare la musica",
      "modalità di riproduzione casuale"
    ]
  },
  pt: {
    HelpIntent: ["Socorro", "Ajude-me", "pode me ajudar"],
    StopIntent: ["Pare", "fora", "Cale-se"],
    CancelIntent: ["cancelar", "deixa pra lá", "esqueça"],
    YesIntent: [
      "OK",
      "claro",
      "eu não me importo",
      "faça",
      "Está bem",
      "parece bom",
      "confirme",
      "está correto",
      "concordo",
      "exatamente",
      "sim",
      "sim por favor",
      "certo"
    ],
    NoIntent: [
      "não",
      "discordo",
      "Na verdade não",
      "não interessado",
      "Eu não quero que",
      "Acho que não",
      "definitivamente não",
      "não fazê-lo",
      "não, obrigado"
    ],
    PauseIntent: ["pausa", "pausar que"],
    ResumeIntent: ["continuar", "currículo", "continuar", "continue"],
    RepeatIntent: ["repetir", "dizer isso de novo", "Repita isso"],
    StartOverIntent: ["recomeçar", "reiniciar", "comece de novo"],
    PreviousIntent: ["volte", "retroceder", "cópia de segurança"],
    NextIntent: ["Próximo", "pular", "passe à frente"],
    LoopOffIntent: ["circuito off"],
    LoopOnIntent: ["ciclo", "laço em", "continuar a jogar este"],
    ShuffleOffIntent: ["parada baralhar", "livrar-se de", "desligue Shuffle"],
    ShuffleOnIntent: ["embaralhar", "Embaralhar", "embaralhar a música", "Modo aleatório"]
  },
  ko: {
    HelpIntent: ["도움", "도와 줘요", "도와주세요"],
    StopIntent: ["중지", "떨어져서", "닥쳐"],
    CancelIntent: ["취소", "신경 쓰지 마", "잊어 버려"],
    YesIntent: [
      "괜찮아",
      "물론이야",
      "그러고 말고",
      "해",
      "확인",
      "소리 좋은",
      "확인",
      "맞습니다",
      "나는 동의한다",
      "바로 그거죠",
      "예",
      "예, 부탁합니다",
      "확실한"
    ],
    NoIntent: [
      "아니",
      "나는 동의",
      "정말",
      "관심이 없다",
      "나는 것을 원하지 않는다",
      "나는 그렇게 생각하지 않아요",
      "절대 아니다",
      "그것을하지 않습니다",
      "고맙지 만 사양 할게"
    ],
    PauseIntent: ["중지", "그 일시 정지"],
    ResumeIntent: ["계속하다", "이력서", "계속하다", "계속"],
    RepeatIntent: ["반복", "다시 말", "다시 말해 봐"],
    StartOverIntent: ["다시 시작하다", "재시작", "다시 시작"],
    PreviousIntent: ["돌아가", "뒤로 건너 뛰기", "백업"],
    NextIntent: ["다음", "건너 뛰기", "앞으로 건너 뛰기"],
    LoopOffIntent: ["루프 해제"],
    LoopOnIntent: ["고리", "에 루프", "이 문제를 계속 연주"],
    ShuffleOffIntent: ["정지 셔플", "오프 셔플", "셔플을 해제"],
    ShuffleOnIntent: ["혼합", "에 셔플", "음악 셔플", "셔플 모드"]
  },
  ru: {
    HelpIntent: ["Помогите", "Помоги мне", "Вы можете помочь мне"],
    StopIntent: ["стоп", "от", "Молчи"],
    CancelIntent: ["Отмена", "неважно", "забудь это"],
    YesIntent: [
      "Ладно",
      "конечно",
      "я не против",
      "сделай это",
      "хорошо",
      "звучит хорошо",
      "подтверждения",
      "это правильно",
      "Я согласен",
      "именно",
      "да",
      "Да, пожалуйста",
      "конечно"
    ],
    NoIntent: [
      "нет",
      "я не согласен",
      "на самом деле, нет",
      "не интересно",
      "Я не хочу, чтобы",
      "Я не думаю, что так",
      "точно нет",
      "не делайте этого",
      "Нет, спасибо"
    ],
    PauseIntent: ["Пауза", "пауза, что"],
    ResumeIntent: ["Продолжать", "продолжить", "Продолжать", "Продолжай"],
    RepeatIntent: ["повторение", "повтори", "повтори это"],
    StartOverIntent: ["начать сначала", "начать сначала", "начать заново"],
    PreviousIntent: ["вернитесь назад", "переход назад", "резервное копирование"],
    NextIntent: ["следующий", "пропускать", "пропустить вперед"],
    LoopOffIntent: ["от петли"],
    LoopOnIntent: ["петля", "петля на", "продолжать играть в этом"],
    ShuffleOffIntent: ["остановка перетасовки", "сваливать", "выключить перетасовать"],
    ShuffleOnIntent: [
      "шарканье",
      "накидывать",
      "перетасовать музыку",
      "режим воспроизведения в случайном порядке"
    ]
  },
  hi: {
    HelpIntent: ["मदद", "मेरी मदद करो", "क्या आप मेरी मदद कर सकते हैं"],
    StopIntent: ["रुकें", "बंद", "चुप रहो"],
    CancelIntent: ["रद्द करना", "कोई बात नहीं", "रहने भी दो"],
    YesIntent: [
      "ठीक है",
      "बेशक",
      "मैं कोई आपत्ति नहीं है",
      "कर दो",
      "ठीक है",
      "बढ़िया है",
      "पुष्टि करें",
      "यह सही है",
      "मैं सहमत हूँ",
      "बिल्कुल सही",
      "हाँ",
      "हाँ कृपया",
      "ज़रूर"
    ],
    NoIntent: [
      "नहीं",
      "मैं असहमत हूं",
      "ज़रुरी नहीं",
      "रुचि नहीं",
      "मैं नहीं करना चाहते कि",
      "मैं ऐसा नहीं सोचता",
      "निश्चित रूप से नहीं",
      "यह मत करो",
      "जी नहीं, धन्यवाद"
    ],
    PauseIntent: ["ठहराव", "थामने कि"],
    ResumeIntent: ["जारी रखें", "बायोडाटा", "जारी रखें", "बढ़ते रहें"],
    RepeatIntent: ["दोहराना", "फिर से कहो", "वापस करो"],
    StartOverIntent: ["प्रारंभ करें", "पुनः आरंभ करें", "फिर से शुरू करें"],
    PreviousIntent: ["वापस जाओ", "वापस छोड़", "बैक अप"],
    NextIntent: ["आगे", "छोड़ें", "छोड़कर आगे बढ़ो"],
    LoopOffIntent: ["पाश बंद"],
    LoopOnIntent: ["पाश", "पर पाश", "इस खेलते रहने के"],
    ShuffleOffIntent: ["बंद की उथल", "फेरबदल करो", "फेरबदल बंद कर देते हैं"],
    ShuffleOnIntent: ["मिश्रण", "फेरबदल जारी", "संगीत शफ़ल", "शफ़ल मोड"]
  },
  th: {
    HelpIntent: ["ช่วยด้วย", "ช่วยฉันด้วย", "คุณสามารถช่วยฉันได้ไหม"],
    StopIntent: ["หยุด", "ปิด", "หุบปาก"],
    CancelIntent: ["ยกเลิก", "ไม่เป็นไร", "ลืมมันไปเถอะ"],
    YesIntent: [
      "ตกลง",
      "แน่นอน",
      "ฉันไม่ขัดข้อง",
      "ทำมัน",
      "ตกลง",
      "ฟังดูเข้าท่า",
      "ยืนยัน",
      "ถูกต้อง",
      "ฉันเห็นด้วย",
      "อย่างแน่นอน",
      "ใช่",
      "ใช่โปรด",
      "แน่ใจ"
    ],
    NoIntent: [
      "ไม่",
      "ฉันไม่เห็นด้วย",
      "ไม่ได้จริงๆ",
      "ไม่สนใจ",
      "ฉันไม่ต้องการที่",
      "ฉันไม่คิดอย่างนั้น",
      "ไม่อย่างแน่นอน",
      "ไม่ได้ทำมัน",
      "ไม่เป็นไรขอบคุณ"
    ],
    PauseIntent: ["หยุด", "หยุดที่"],
    ResumeIntent: ["ต่อ", "ประวัติย่อ", "ต่อ", "ทำต่อไป"],
    RepeatIntent: ["ทำซ้ำ", "บอกว่าอีกครั้ง", "ซ้ำว่า"],
    StartOverIntent: ["เริ่มต้นใหม่", "เริ่มต้นใหม่", "เริ่มต้นอีกครั้ง"],
    PreviousIntent: ["กลับไป", "ข้ามกลับ", "สำรอง"],
    NextIntent: ["ต่อไป", "กระโดด", "ข้ามไปข้างหน้า"],
    LoopOffIntent: ["ปิดห่วง"],
    LoopOnIntent: ["ห่วง", "ห่วง", "ให้เล่นนี้"],
    ShuffleOffIntent: ["หยุดสับ", "สับเปลี่ยนออก", "ปิดการสับเปลี่ยน"],
    ShuffleOnIntent: ["สับเปลี่ยน", "สลับบน", "สลับเพลง", "โหมดสับเปลี่ยน"]
  },
  id: {
    HelpIntent: ["Tolong", "tolong aku", "Bisakah kamu membantuku"],
    StopIntent: ["berhenti", "mati", "diam"],
    CancelIntent: ["membatalkan", "lupakan", "lupakan"],
    YesIntent: [
      "baik",
      "tentu saja",
      "Saya tidak keberatan",
      "lakukan",
      "baik",
      "kedengarannya bagus",
      "Konfirmasi",
      "itu benar",
      "saya setuju",
      "persis",
      "Iya",
      "ya silahkan",
      "Tentu"
    ],
    NoIntent: [
      "tidak",
      "saya tidak setuju",
      "tidak juga",
      "tidak tertarik",
      "Saya tidak ingin itu",
      "Saya tidak berpikir begitu",
      "tentu saja tidak",
      "jangan lakukan itu",
      "tidak, terima kasih"
    ],
    PauseIntent: ["berhenti sebentar", "jeda yang"],
    ResumeIntent: ["terus", "lanjut", "terus", "teruskan"],
    RepeatIntent: ["ulang", "katakan itu lagi", "ulangi itu"],
    StartOverIntent: ["memulai", "mengulang kembali", "mulai lagi"],
    PreviousIntent: ["kembali", "melompat kembali", "mundur"],
    NextIntent: ["lanjut", "melewatkan", "melompat ke depan"],
    LoopOffIntent: ["lingkaran off"],
    LoopOnIntent: ["putaran", "loop pada", "terus bermain ini"],
    ShuffleOffIntent: ["berhenti menyeret", "menyingkiri", "mematikan mengocok"],
    ShuffleOnIntent: ["kocokan", "mengocok di", "mengocok musik", "mode acak"]
  },
  da: {
    HelpIntent: ["Hjælp", "hjælp mig", "kan du hjælpe mig"],
    StopIntent: ["hold op", "af", "hold kæft"],
    CancelIntent: ["afbestille", "Glem det", "Glem det"],
    YesIntent: [
      "okay",
      "selvfølgelig",
      "Jeg har ikke noget imod",
      "gør det",
      "Okay",
      "lyder godt",
      "bekræfte",
      "det er korrekt",
      "jeg er enig",
      "Nemlig",
      "Ja",
      "ja tak",
      "jo da"
    ],
    NoIntent: [
      "ingen",
      "jeg er uenig",
      "ikke rigtig",
      "ikke interesseret",
      "Jeg ønsker ikke at",
      "Jeg tror det ikke",
      "absolut ikke",
      "gør det ikke",
      "Nej tak"
    ],
    PauseIntent: ["pause", "pause, at"],
    ResumeIntent: ["Blive ved", "Genoptag", "Blive ved", "Fortsæt"],
    RepeatIntent: ["gentage", "sig det igen", "gentage, at"],
    StartOverIntent: ["start forfra", "genstart", "starte igen"],
    PreviousIntent: ["gå tilbage", "springe tilbage", "sikkerhedskopiere"],
    NextIntent: ["Næste", "springe", "springe frem"],
    LoopOffIntent: ["loop off"],
    LoopOnIntent: ["loop", "loop på", "fortsætter med at spille dette"],
    ShuffleOffIntent: ["stop-blander", "shuffle", "slukke shuffle"],
    ShuffleOnIntent: ["shuffle", "shuffle på", "shuffle musikken", "shuffle-mode"]
  },
  no: {
    HelpIntent: ["hjelp", "hjelp meg", "kan du hjelpe meg"],
    StopIntent: ["Stoppe", "av", "hold kjeft"],
    CancelIntent: ["Avbryt", "glem det", "glem det"],
    YesIntent: [
      "greit",
      "selvfølgelig",
      "Jeg har ikke noe imot",
      "gjør det",
      "ok",
      "høres bra ut",
      "bekrefte",
      "det er riktig",
      "jeg er enig",
      "nøyaktig",
      "ja",
      "Ja takk",
      "sikker"
    ],
    NoIntent: [
      "Nei",
      "jeg er uenig",
      "ikke egentlig",
      "ikke interessert",
      "Jeg ønsker ikke at",
      "Jeg tror ikke det",
      "definitivt ikke",
      "ikke gjør det",
      "Nei takk"
    ],
    PauseIntent: ["pause", "pause som"],
    ResumeIntent: ["Fortsette", "gjenoppta", "Fortsette", "Fortsett"],
    RepeatIntent: ["gjenta", "si det igjen", "gjenta det"],
    StartOverIntent: ["begynne på nytt", "omstart", "starte på nytt"],
    PreviousIntent: ["gå tilbake", "hoppe tilbake", "sikkerhetskopiere"],
    NextIntent: ["neste", "hoppe", "hoppe fremover"],
    LoopOffIntent: ["sløyfe off"],
    LoopOnIntent: ["Løkke", "sløyfe på", "fortsette å spille dette"],
    ShuffleOffIntent: ["stop shuffling", "shuffle", "slå av shuffle"],
    ShuffleOnIntent: ["tilfeldig rekkefølge", "shuffle på", "shuffle musikken", "shuffle-modus"]
  },
  nl: {
    HelpIntent: ["helpen", "Help mij", "kun je me helpen"],
    StopIntent: ["hou op", "uit", "hou je mond"],
    CancelIntent: ["Annuleer", "laat maar", "laat maar"],
    YesIntent: [
      "Oke",
      "natuurlijk",
      "Ik vind het niet erg",
      "doe het",
      "OK",
      "klinkt goed",
      "bevestigen",
      "dat is correct",
      "ik ga akkoord",
      "precies",
      "Ja",
      "Ja graag",
      "zeker"
    ],
    NoIntent: [
      "Nee",
      "ben ik het niet mee eens",
      "niet echt",
      "niet geïnteresseerd",
      "Ik wil niet dat",
      "Ik denk het niet",
      "zeker niet",
      "doe het niet",
      "Nee, dank u wel"
    ],
    PauseIntent: ["pauze", "pauzeren dat"],
    ResumeIntent: ["doorgaan met", "hervatten", "doorgaan met", "ga door"],
    RepeatIntent: ["herhaling", "Zeg dat nog eens", "herhaal dat"],
    StartOverIntent: ["begin opnieuw", "herstarten", "opnieuw beginnen"],
    PreviousIntent: ["ga terug", "overspringen terug", "een back-up"],
    NextIntent: ["De volgende", "overspringen", "Spring vooruit"],
    LoopOffIntent: ["lus off"],
    LoopOnIntent: ["lus", "lus op", "Bewaar deze spelen"],
    ShuffleOffIntent: ["stop schuifelen", "heenslenteren", "uitschakelen shuffle"],
    ShuffleOnIntent: ["schuifelen", "shuffle aan", "shuffle de muziek", "Shuffle modus"]
  },
  sv: {
    HelpIntent: ["hjälp", "hjälp mig", "kan du hjälpa mig"],
    StopIntent: ["sluta", "av", "håll käften"],
    CancelIntent: ["annullera", "Glöm det", "Glöm det"],
    YesIntent: [
      "Okej",
      "självklart",
      "Jag har inget emot",
      "gör det",
      "ok",
      "låter bra",
      "bekräfta",
      "det stämmer",
      "jag håller med",
      "exakt",
      "ja",
      "Ja tack",
      "Säker"
    ],
    NoIntent: [
      "Nej",
      "jag håller inte med",
      "inte riktigt",
      "inte intresserad",
      "Jag vill inte att",
      "Jag tror inte det",
      "definitivt inte",
      "gör det inte",
      "Nej tack"
    ],
    PauseIntent: ["paus", "pausa att"],
    ResumeIntent: ["Fortsätta", "återuppta", "Fortsätta", "Fortsätt"],
    RepeatIntent: ["upprepa", "säga det igen", "repetera det"],
    StartOverIntent: ["börja om", "omstart", "börja om"],
    PreviousIntent: ["gå tillbaka", "hoppa tillbaka", "backa upp"],
    NextIntent: ["Nästa", "hoppa", "hoppa framåt"],
    LoopOffIntent: ["slinga av"],
    LoopOnIntent: ["slinga", "ögla på", "fortsätta spela här"],
    ShuffleOffIntent: ["stopp skyffling", "shuffle", "stänga shuffle"],
    ShuffleOnIntent: ["blanda", "shuffle på", "blanda musiken", "blandningsläget"]
  }
};
